name: skript-particle
author: Sovde
website: https://github.com/sovdeeth/skript-particle
description: Create complex effects with particles
version: 1.0.2-alpha
api-version: 1.17
main: com.sovdee.skriptparticles.SkriptParticle
depend: [Skript]
softdepend: [SkBee]
